# Form implementation generated from reading ui file 'd:\Codes\Simulations\Hourglass\NoEngine\render.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Render(object):
    def setupUi(self, Render):
        Render.setObjectName("Render")
        Render.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(Render)
        self.gridLayout.setObjectName("gridLayout")
        self.canvas_layout = QtWidgets.QVBoxLayout()
        self.canvas_layout.setObjectName("canvas_layout")
        self.gridLayout.addLayout(self.canvas_layout, 0, 0, 1, 4)
        self.frame_label = QtWidgets.QLabel(parent=Render)
        self.frame_label.setObjectName("frame_label")
        self.gridLayout.addWidget(self.frame_label, 1, 3, 1, 1)
        self.frame_slider = QtWidgets.QSlider(parent=Render)
        self.frame_slider.setProperty("value", 1)
        self.frame_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.frame_slider.setObjectName("frame_slider")
        self.gridLayout.addWidget(self.frame_slider, 1, 2, 1, 1)
        self.start_button = QtWidgets.QPushButton(parent=Render)
        self.start_button.setObjectName("start_button")
        self.gridLayout.addWidget(self.start_button, 1, 0, 1, 1)
        self.stop_button = QtWidgets.QPushButton(parent=Render)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout.addWidget(self.stop_button, 1, 1, 1, 1)

        self.retranslateUi(Render)
        QtCore.QMetaObject.connectSlotsByName(Render)

    def retranslateUi(self, Render):
        _translate = QtCore.QCoreApplication.translate
        Render.setWindowTitle(_translate("Render", "渲染"))
        self.frame_label.setText(_translate("Render", "Frame"))
        self.start_button.setText(_translate("Render", "开始"))
        self.stop_button.setText(_translate("Render", "停止"))
